### ISSUE TITLE
readme: link for ParadiseOS is broken

### ISSUE THREAD

**Issue by maphew** [hundredrabbits/Paradise#38]

**Comment by microlith57** [comment]
The link used to redirect to [XXIIVV/Parade](https://www.github.com/XXIIVV/Parade) but it looks like that repo was deleted, probably because it was only a `README.md` file.
If you want to see, I have a fork [here](https://github.com/microlith57/Parade) (with a crude ruby implementation of a networked Paradise on the [`ruby` branch](https://github.com/microlith57/Parade/tree/ruby)).

I'll open a PR to remove the reference here.
